"""init 3

Revision ID: 724bd5f6925a
Revises: d3995268133f
Create Date: 2018-11-25 17:15:20.927657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724bd5f6925a'
down_revision = 'd3995268133f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###
